// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DangKyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dangKy() {
    driver.get("https://www.topcv.vn/sign-up");
    driver.manage().window().setSize(new Dimension(1936, 1096));
    driver.findElement(By.name("fullname")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("vanquy03.work@gmail.com");
    driver.findElement(By.id("password")).sendKeys("@Vanquy03");
    driver.findElement(By.id("password_confirmation")).sendKeys("@Vanquy03");
    driver.findElement(By.cssSelector(".form-group:nth-child(6) .toggle-password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(7) .toggle-password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("form-register"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("form-register")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(7) .toggle-password")).click();
    driver.findElement(By.cssSelector(".btn-sign")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-sign"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
