// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC_01', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC_01', async function() {
    await driver.get("https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-luong-cung-deal-tu-8-12-trieu-phu-cap-hoa-hong-thuong/1331577.html?ta_source=BoxFeatureJob_QuickView")
    await driver.findElement(By.linkText("Ứng tuyển ngay")).click()
    await driver.findElement(By.linkText("Chọn CV")).click()
    await driver.findElement(By.id("filer_input")).sendKeys("C:\\fakepath\\my_cv.pdf")
    await driver.findElement(By.css("#frm-upload > .form-group:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css("#frm-upload > .form-group:nth-child(2) > .form-control")).sendKeys(" ")
    await driver.findElement(By.css(".col-xs-6:nth-child(1) > .mb-0 > .form-control")).click()
    await driver.findElement(By.css(".col-xs-6:nth-child(1) > .mb-0 > .form-control")).sendKeys("email@gmail.com")
    await driver.findElement(By.css(".col-xs-6:nth-child(2) > .mb-0 > .form-control")).click()
    await driver.findElement(By.css(".col-xs-6:nth-child(2) > .mb-0 > .form-control")).sendKeys("123456789")
    await driver.findElement(By.id("btn-apply")).click()
  })
})
